### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by dearminder** [CortexPE/HRKMigrator#1]
[Server thread/INFO]: [HRKMigrator] Migrating 'Owner' group permissions..
[Server thread/CRITICAL]: ErrorException: "Illegal offset type in isset or empty" (EXCEPTION) in "plugins/Hierarchy_dev-53.phar/src/CortexPE/Hierarchy/member/MemberFactory" at line 73

**Comment by CortexPE** [comment]
closing because this issue stale & probably outdated... please re-open if it still does exist nowadays

you probably should've pasted the stacktrace anyways reeeee
